// <auto-generated />
using System;
using GeoSat.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GeoSat.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607215218_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoSat.API.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<string>("DsDescricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<DateTime>("DtGerado")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_GERADO");

                    b.Property<DateTime?>("DtResolvido")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_RESOLVIDO");

                    b.Property<DateTime?>("DtVisualizado")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_VISUALIZADO");

                    b.Property<int>("IdTalhao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TALHAO");

                    b.Property<string>("StStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ST_STATUS");

                    b.Property<string>("TpNivel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TP_NIVEL");

                    b.Property<string>("TpOrigem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TP_ORIGEM");

                    b.Property<string>("TpTipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TP_TIPO");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdTalhao");

                    b.ToTable("TB_GST_ALERTA");
                });

            modelBuilder.Entity("GeoSat.API.Models.Configuracao", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONFIG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfig"));

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<int>("IdTalhao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TALHAO");

                    b.Property<int>("NrJanelaFusaoHoras")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_JANELA_FUSAO_HORAS");

                    b.Property<decimal>("NrThresholdNdviMin")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NR_THRESHOLD_NDVI_MIN");

                    b.Property<decimal>("NrThresholdUmidMin")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NR_THRESHOLD_UMID_MIN");

                    b.HasKey("IdConfig");

                    b.HasIndex("IdTalhao")
                        .IsUnique();

                    b.ToTable("TB_GST_CONFIGURACAO");
                });

            modelBuilder.Entity("GeoSat.API.Models.ImagemSatelital", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_IMAGEM");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagem"));

                    b.Property<string>("DsErro")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_ERRO");

                    b.Property<string>("DsFonte")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_FONTE");

                    b.Property<string>("DsStatusProc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_STATUS_PROC");

                    b.Property<DateTime>("DtCaptura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CAPTURA");

                    b.Property<DateTime?>("DtProcessado")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_PROCESSADO");

                    b.Property<int>("IdTalhao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TALHAO");

                    b.Property<decimal?>("NrNdvi")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NR_NDVI");

                    b.HasKey("IdImagem");

                    b.HasIndex("IdTalhao");

                    b.ToTable("TB_GST_IMAGEM_SATELITAL");
                });

            modelBuilder.Entity("GeoSat.API.Models.LeituraSensor", b =>
                {
                    b.Property<int>("IdLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLeitura"));

                    b.Property<DateTime>("DtLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LEITURA");

                    b.Property<DateTime>("DtRecebida")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_RECEBIDA");

                    b.Property<string>("FlTransmitida")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FL_TRANSMITIDA");

                    b.Property<int>("IdSensor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<decimal?>("NrLuminosidade")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NR_LUMINOSIDADE");

                    b.Property<decimal>("NrTempAr")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NR_TEMP_AR");

                    b.Property<decimal>("NrUmidadeSolo")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NR_UMIDADE_SOLO");

                    b.HasKey("IdLeitura");

                    b.HasIndex("IdSensor");

                    b.ToTable("TB_GST_LEITURA_SENSOR");
                });

            modelBuilder.Entity("GeoSat.API.Models.LogAlerta", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOG");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("DsAcao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_ACAO");

                    b.Property<string>("DsObservacao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_OBSERVACAO");

                    b.Property<string>("DsOrigem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_ORIGEM");

                    b.Property<DateTime>("DtEvento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_EVENTO");

                    b.Property<int>("IdAlerta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    b.HasKey("IdLog");

                    b.HasIndex("IdAlerta");

                    b.ToTable("TB_GST_LOG_ALERTA");
                });

            modelBuilder.Entity("GeoSat.API.Models.Produtor", b =>
                {
                    b.Property<int>("IdProdutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRODUTOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProdutor"));

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("FlAtivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_NOME");

                    b.Property<string>("NrCpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NR_CPF");

                    b.Property<string>("NrTelefone")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NR_TELEFONE");

                    b.HasKey("IdProdutor");

                    b.ToTable("TB_GST_PRODUTOR");
                });

            modelBuilder.Entity("GeoSat.API.Models.Propriedade", b =>
                {
                    b.Property<int>("IdPropriedade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROPRIEDADE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropriedade"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("FlAtiva")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FL_ATIVA");

                    b.Property<int>("IdProdutor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRODUTOR");

                    b.Property<string>("NmMunicipio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_MUNICIPIO");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_NOME");

                    b.Property<decimal>("NrAreaHa")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NR_AREA_HA");

                    b.Property<string>("SgEstado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SG_ESTADO");

                    b.HasKey("IdPropriedade");

                    b.HasIndex("IdProdutor");

                    b.ToTable("TB_GST_PROPRIEDADE");
                });

            modelBuilder.Entity("GeoSat.API.Models.RefreshTokenNet", b =>
                {
                    b.Property<int>("IdRefresh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REFRESH");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRefresh"));

                    b.Property<string>("DsToken")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_TOKEN");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<DateTime>("DtExpiracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_EXPIRACAO");

                    b.Property<string>("FlRevogado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FL_REVOGADO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdRefresh");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_GST_REFRESH_TOKEN_NET");
                });

            modelBuilder.Entity("GeoSat.API.Models.Sensor", b =>
                {
                    b.Property<int>("IdSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSensor"));

                    b.Property<string>("CdIdentificadorHw")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CD_IDENTIFICADOR_HW");

                    b.Property<string>("DsLocalizacao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_LOCALIZACAO");

                    b.Property<DateTime>("DtInstalacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INSTALACAO");

                    b.Property<string>("FlAtivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<int>("IdTalhao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TALHAO");

                    b.HasKey("IdSensor");

                    b.HasIndex("IdTalhao");

                    b.ToTable("TB_GST_SENSOR");
                });

            modelBuilder.Entity("GeoSat.API.Models.Talhao", b =>
                {
                    b.Property<int>("IdTalhao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TALHAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTalhao"));

                    b.Property<string>("DsCultura")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_CULTURA");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("FlAtivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<int>("IdPropriedade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROPRIEDADE");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_NOME");

                    b.Property<decimal>("NrAreaHa")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("NR_AREA_HA");

                    b.HasKey("IdTalhao");

                    b.HasIndex("IdPropriedade");

                    b.ToTable("TB_GST_TALHAO");
                });

            modelBuilder.Entity("GeoSat.API.Models.UsuarioNet", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("DsRole")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_ROLE");

                    b.Property<string>("DsSenhaHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_SENHA_HASH");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIACAO");

                    b.Property<string>("FlAtivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FL_ATIVO");

                    b.Property<string>("NmNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_NOME");

                    b.HasKey("IdUsuario");

                    b.HasIndex("DsEmail")
                        .IsUnique();

                    b.ToTable("TB_GST_USUARIO_NET");
                });

            modelBuilder.Entity("GeoSat.API.Models.Alerta", b =>
                {
                    b.HasOne("GeoSat.API.Models.Talhao", "Talhao")
                        .WithMany("Alertas")
                        .HasForeignKey("IdTalhao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talhao");
                });

            modelBuilder.Entity("GeoSat.API.Models.Configuracao", b =>
                {
                    b.HasOne("GeoSat.API.Models.Talhao", "Talhao")
                        .WithOne("Configuracao")
                        .HasForeignKey("GeoSat.API.Models.Configuracao", "IdTalhao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talhao");
                });

            modelBuilder.Entity("GeoSat.API.Models.ImagemSatelital", b =>
                {
                    b.HasOne("GeoSat.API.Models.Talhao", "Talhao")
                        .WithMany("ImagensSatelitais")
                        .HasForeignKey("IdTalhao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talhao");
                });

            modelBuilder.Entity("GeoSat.API.Models.LeituraSensor", b =>
                {
                    b.HasOne("GeoSat.API.Models.Sensor", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("IdSensor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GeoSat.API.Models.LogAlerta", b =>
                {
                    b.HasOne("GeoSat.API.Models.Alerta", "Alerta")
                        .WithMany("Logs")
                        .HasForeignKey("IdAlerta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("GeoSat.API.Models.Propriedade", b =>
                {
                    b.HasOne("GeoSat.API.Models.Produtor", "Produtor")
                        .WithMany("Propriedades")
                        .HasForeignKey("IdProdutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produtor");
                });

            modelBuilder.Entity("GeoSat.API.Models.RefreshTokenNet", b =>
                {
                    b.HasOne("GeoSat.API.Models.UsuarioNet", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GeoSat.API.Models.Sensor", b =>
                {
                    b.HasOne("GeoSat.API.Models.Talhao", "Talhao")
                        .WithMany("Sensores")
                        .HasForeignKey("IdTalhao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talhao");
                });

            modelBuilder.Entity("GeoSat.API.Models.Talhao", b =>
                {
                    b.HasOne("GeoSat.API.Models.Propriedade", "Propriedade")
                        .WithMany("Talhoes")
                        .HasForeignKey("IdPropriedade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("GeoSat.API.Models.Alerta", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("GeoSat.API.Models.Produtor", b =>
                {
                    b.Navigation("Propriedades");
                });

            modelBuilder.Entity("GeoSat.API.Models.Propriedade", b =>
                {
                    b.Navigation("Talhoes");
                });

            modelBuilder.Entity("GeoSat.API.Models.Sensor", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("GeoSat.API.Models.Talhao", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Configuracao");

                    b.Navigation("ImagensSatelitais");

                    b.Navigation("Sensores");
                });
#pragma warning restore 612, 618
        }
    }
}
